config/routes.rb
HvO::Application.routes.draw do

  constraints :subdomain => /.+/ do
    get '/' => 'initiatives#show'
    get '/wishlist' => "items#dashboard"
    get '/all_available_dates' => "available_dates#availability_dashboard"
    get '/profiles' => "profiles#index"

    
    get '/initiative/edit' => "initiatives#edit"
    delete '/initiative', :to => "initiatives#destroy"
    get '/initiative', :to => "initiatives#show"
    patch '/initiative', :to => "initiatives#update"
    resources :initiatives
    resources :invitations
  end
  root to: "home#index"

  get "/invitations/:token/accept", :to => "invitations#accept", :as => "accept_invitation"
  post "/invitations/:token", :to => "invitations#register", :as => "register_user_via_invitation"

  resources :initiatives do
    collection do
      get "new_from_bucket_group", :to => "initiatives#new_from_bucket_group"
      get "new_with_buddy", to: "initiatives#new_with_buddy"
      post "create_with_buddy", to: "initiatives#create_with_buddy"
    end
  end
  resources :bucket_groups, except: :index  do
    member do
      get 'admin_edit'
      delete 'destroy_user/:bgu_id', :to => "bucket_groups#destroy_user", as: "destroy_user"
    end
    collection do
      get "new_unregistered", :to => "bucket_groups#new_unregistered"
    end
    resources :invitations
  end

	get "waardeverbinder", :as => "waardeverbinder_info", :to => "waardeverbinder#info"
  get "disclaimer", :as => "disclaimer", :to => "home#disclaimer"

	post '/auth/:provider/callback' => 'authentications#create'

  resources :messages, :except => [:edit, :show]
	get "feedback" => "messages#new"

  get "profiles/all", :as => "all_profiles", :to => "profiles#super_admin_index"
  get "initiative_profiles", :as => "all_initiative_profiles", :to => "profiles#initiative_user_index"
  resources :profiles, :except => [:index] do
		resources :available_dates, :except => [:show]
    get "contribution" => "profiles#contribution"
	end
  

  devise_for :users, :skip => [:registrations]                                          
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
      patch 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
      delete 'users/:id' => 'devise/registrations#destroy'            
    end

	devise_scope :user do
		get "login", :to => "devise/sessions#new"
		get "logout", :to => "devise/sessions#destroy"
	end

  resources :user_roles, :except => [:show, :edit, :index] 
  get '/calendar(/:year(/:month))' => 'projects#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
	resources :items, :except => [:index, :show] #loose items
	get "dashboard", :to => "items#dashboard"
  get "availability_dashboard", :to => "available_dates#availability_dashboard"
	resources :links, :only => [:index]

  resources :projects, :except => [:show] do
    resources :items, :only => [:index, :update] #items belonging to projects
  end

  resources :messages, :except => [:index]

  scope "/admin" do
    resources :users
    get 'feedback', :to => 'messages#index', :as => "admin_feedback"
    get 'profiles', :to => "profiles#super_admin_index", :as => "admin_profiles"
    get 'initiatives', :to => "initiatives#index", :as => "admin_initiatives"
    get 'bucket_groups', to: "bucket_groups#index", :as => "admin_bucket_groups"
  end

	get "projects/info"
	get "available_dates/info"
	get "items/info"
	get "profiles/:id/info", :to => "profiles#info", :as => "profile_info"
	get "profiles/:profile_id/item/:id", :to => "profiles#remove_item", :as => "remove_item_from_profile"

  get "terms_and_conditions", :as => "terms_and_conditions", :to => "home#terms_and_conditions"

end

app/models/initiative.rb
class Initiative
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, :type => String
  field :location, :type => String
  field :description, :type => String
  field :slug, :type => String

  field :patient_email, type: String
  field :patient_name, type: String
  field :buddy_email, type: String
  field :buddy_name, type: String

  before_validation :build_slug

  validates_presence_of :name
  validates_uniqueness_of :slug, :message => "Naam bestaat al."
  validates_exclusion_of :slug, :in => ["www", "bucketline"], :message => "Naam is niet toegestaan."
  validates_format_of :patient_email, with: /[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/i, allow_blank: true
  validates_format_of :buddy_email, with: /[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/i, allow_blank: true

  has_many :user_roles, :dependent => :destroy #Roles for an initiative such as admin or superadmin are tracked via the userrole model
  has_many :invitations, :dependent => :destroy, as: :invitationable

	has_many :projects #, :dependent => :destroy
	has_many :items #, :dependent => :destroy #loose items

	def build_slug
		self.slug = self.name.downcase.gsub(' ', '-').gsub("'", "").gsub("&", "").gsub("+", "").gsub("#", "").gsub("@", "")
	end

	def admins
		user_roles = UserRole.where(:initiative_id => self.id, :admin => true)
		admins = []
		user_roles.each do |user_role|
			if user_role.user
				admins << user_role.user
			end
		end
		admins
	end

	def users
		user_roles = UserRole.where(:initiative_id => self.id)
		users = []
		user_roles.each do |user_role|
			if user_role.user
				users << user_role.user
			end
		end
		users
	end

  def events_hash_for_month(date=Date.today)
    events_hash = {}
    self.projects.where(start_at: date.beginning_of_month..date.end_of_month).each do |project|
      events_hash[project.start_at.day] = project
    end
    return events_hash
  end

  def user_is_admin?(user)
    (UserRole.where(:initiative_id => self.id, user_id: user.id).present? and UserRole.where(:initiative_id => self.id, user_id: user.id).first.admin) || user.super_admin
  end

end

app/controllers/initiatives_controller.rb
class InitiativesController < ApplicationController
  before_filter :get_initiative, :only => [:edit, :show, :update, :destroy]
  before_filter :get_bucket_group, only: [:new_from_bucket_group, :create]
  # before_filter :authenticate_super_admin, :except => [:edit, :update, :show]
  before_filter :get_initiative_from_subdomain, only: [:show, :edit, :update]
  before_filter :authenticate_user_for_initiative, :only => [:show]
  # before_filter :authenticate_admin_for_initiative, :only => [:edit, :update]
  before_filter :authenticate_admin_for_bucket_group, :only => [:new_from_bucket_group]
  before_filter :authenticate_bucket_line_creator, only: [:new_with_buddy, :create_with_buddy]

  # GET /initiatives
  # GET /initiatives.json
  def index
    @initiatives = Initiative.all
  end

  # GET /initiatives/1
  # GET /initiatives/1.json
  def show
    @user_role = @initiative.user_roles.where(:user_id => current_user.id).last

    @admin_names = []
    @user_names = []
    @extra_user_count = 0

    @initiative.user_roles.each do |user_role|
      if user_role.admin
        @admin_names << user_role.user.name
      elsif user_role.user.profile.show_name_in_overview
        @user_names << user_role.user.name
      else
        @extra_user_count += 1
      end
    end
  end

  # GET /initiatives/new
  # GET /initiatives/new.json
  def new
    @initiative = Initiative.new

    if params[:bucket_group_id].present?
      @bucket_group = BucketGroup.find(params[:bucket_group_id])
    end

    respond_to do |format|
      format.html do
        if @bucket_group.present?
          render "new_bucket_group"
        end
      end
      format.json { render json: @initiative }
    end
  end

  def new_with_buddy
    @initiative = Initiative.new
    respond_to do |format|
      format.html do
      end
      format.json { render json: @initiative }
    end
  end

  def new_from_bucket_group
    @initiative = Initiative.new
    @bucket_group = BucketGroup.find(params[:bucket_group_id])

    respond_to do |format|
      format.html do
        render "new_bucket_group"
      end
      format.json { render json: @initiative }
    end

  end

  # GET /initiatives/1/edit
  def edit
  end

  # POST /initiatives
  # POST /initiatives.json
  def create
    if params[:initiative][:bucket_group_id].present?
      bucket_group = BucketGroup.find(params[:initiative][:bucket_group_id])
      params[:initiative].delete(:bucket_group_id)
    end

    @initiative = Initiative.new(params[:initiative])

    respond_to do |format|
      if @initiative.save

        if bucket_group.present?
          bucket_group.users.each do |bu|
            @initiative.user_roles.create(user: bu.user)
          end
        end

        admin_user = @initiative.user_roles.find_or_create_by(:user_id => current_user.id) #Make the current user automatically admin of his newly created initiative
        admin_user.admin = true
        admin_user.save                                                                                           #
        format.html { redirect_to initiative_url(:subdomain => @initiative.slug), :notice => "Bucket Line is aangemaakt." }
      else
        format.html { render action: "new" }
        format.json { render json: @initiative.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_with_buddy
    @initiative = Initiative.new(params[:initiative])
    if params[:initiative][:patient_email].present?

      @invitation_patient = @initiative.invitations.new(email: params[:initiative][:patient_email], name: params[:initiative][:patient_name], admin: true)
      if params[:initiative][:buddy_email].present?
        @invitation_buddy = @initiative.invitations.new(email: params[:initiative][:buddy_email], name: params[:initiative][:buddy_name], admin: true)
      end
      patient_email_present = true
    else
      patient_email_present = false
    end

    respond_to do |format|
      if patient_email_present && @initiative.save && @invitation_patient.save
        buddy_name = nil
        if @invitation_buddy.present?
          @invitation_buddy.save
          buddy_name = @invitation_buddy.name          
        end
        InvitationPatientMailer.invitation_email(current_user.name, accept_invitation_url(:token => @invitation_patient.token, :subdomain => false), @invitation_patient.email, @invitation_patient.name, buddy_name).deliver
        if @invitation_buddy.present?
          InvitationBuddyMailer.invitation_email(current_user.name, accept_invitation_url(:token => @invitation_buddy.token, :subdomain => false), @invitation_buddy.email, @invitation_buddy.name, @invitation_patient.name).deliver
        end
                                                                      #
        format.html { redirect_to initiative_url(:subdomain => @initiative.slug), :notice => "Bucket Line is aangemaakt." }
      else
        format.html do
          flash[:alert] = "Bucketline aanmaken mislukt. #{patient_email_present ? '' : 'Vul een emailadres in voor de patient' }"
          render action: "new_with_buddy"
        end
        format.json { render json: @initiative.errors, status: :unprocessable_entity }
      end
    end

  end

  # PUT /initiatives/1
  # PUT /initiatives/1.json
  def update
    #@initiative = Initiative.find(params[:id])
    if @initiative.update_attributes(params[:initiative])
      redirect_to edit_initiative_url(:subdomain => @initiative.slug, id: @initiative.id), :notice => "Bucket Line is aangepast."
    else
      render action: "edit"
    end
  end

  # DELETE /initiatives/1
  # DELETE /initiatives/1.json
  def destroy
    @initiative = Initiative.where(slug: request.subdomain).first
    @initiative.destroy

    respond_to do |format|
      format.html { redirect_to admin_initiatives_url + "?no_redirect=true" }
      format.json { head :no_content }
    end
  end

  private 

  def get_initiative_from_subdomain
    if request.subdomain
      @initiative = Initiative.where(slug: request.subdomain).first
    else
      @initiative = Initiative.find(params[:id])
    end
  end

  def get_bucket_group
    @bucket_group = nil
    if params[:bucket_group_id].present?
      @bucket_group = BucketGroup.find(params[:bucket_group_id]) 
    end
    if params[:initiative].present? and params[:initiative][:bucket_group_id].present?
      @bucket_group = BucketGroup.find(params[:initiative][:bucket_group_id]) 
    end
  end

end

app/helpers/initiatives_helper.rb
module InitiativesHelper
	def initiatives_to_sentence(initiatives)
		sentence = []
		initiatives.each do |initiative|
			if initiative
				sentence << initiative.name
			end
		end
		sentence.to_sentence
	end
end

app/views/initiatives/_form.html.erb
<%= form_for(@initiative) do |f| %>
  <% if @initiative.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@initiative.errors.count, "error") %> prohibited this initiative from being saved:</h2>

      <ul>
      <% @initiative.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit "Bucket Line aanmaken" %>
  </div>
<% end %>

app/views/initiatives/_form.html.haml
- if request.path_parameters[:action] == 'edit' then action = :update else action = :create end
= form_for @initiative, :url => {:controller => :initiatives, :action => action, :host => request.host} do |f|
  - if @initiative.errors.any?
    %h6.alert
      = pluralize(@initiative.errors.count, "fouten")

  = f.label :name, class: form_error_class(@initiative.errors[:name])
  = f.text_field :name, class: form_error_class(@initiative.errors[:name])
  - if @initiative.errors[:slug].present?
    %small.error #{@initiative.errors[:slug].first}

  = f.label :location, class: form_error_class(@initiative.errors[:location])
  = f.text_field :location, class: form_error_class(@initiative.errors[:location])
  - if @initiative.errors[:location].present?
    %small.error #{@initiative.errors[:location].first}

  = f.label :description, class: form_error_class(@initiative.errors[:description])
  = f.text_area :description, class: form_error_class(@initiative.errors[:description])
  - if @initiative.errors[:description].present?
    %small.error #{@initiative.errors[:description].first}

  - if @bucket_group.present?
    = f.hidden_field :bucket_group_id, value: @bucket_group.id

  - if request.path_parameters[:action] == 'new' then onclick_action = "_gaq.push(['_trackEvent', 'Initiative', 'Placement']);" else onclick_action = "" end
  = f.submit "Opslaan", class: "button"

app/views/initiatives/edit.html.haml
- content_for :header do
  = render :partial => "shared/sub_nav" 
  
= render :partial => 'initiatives/form'

app/views/initiatives/index.html.erb
<div class="row">
	<div class="span12">
		<h2>Bucket Line brengt mensen samen om in een tijdelijke en persoonlijke noodsituatie, een steun te zijn door kleine klussen te doen.</h2>
	</div>
</div>
<hr>
<div class="row">
	<div class="span6">
		<h3>Bucket Line</h3>
		<p>Een Bucket Line bestaat uit je eigen vertrouwde netwerk: de buurt, familie, het bedrijf, de school, de vereniging. Als bij jou of bij een ander in jouw Bucket Line netwerk een tijdelijke noodsituatie ontstaat, zoals een sterfgeval of ernstige ziekte in een gezin, zorgt de Bucket Line voor een gezamenlijke aanpak van kleine klussen die gedaan moeten worden, zoals boodschappen doen, poetsen, koken, of licht administratief werk.</p> 
	</div>
	<div class="span6">
		<h3>De Bucket Line waardeverbinder</h3>
		<p>Met deze website kun je je eigen Bucket Line opstellen. Je kunt het zien als een interactieve agenda. Op basis van de beschikbaarheid van de leden van de Bucket Line en wat er binnen de Bucket Line aanwezig is, worden door een hulpbehoevende kleine klussen ingepland. Denk bijvoorbeeld aan koken, of naar de apotheek rijden. In een agenda kunnen de leden alle klussen bekijken, en meteen hun hulp aanbieden.</p><p>Op dit punt zijn we de Bucket Line waardeverbinder nog aan het testen. Neem contact op het Bucket Line (info@bucketline.nl) als je wilt helpen met testen.</p>
	</div>	
</div>
<hr>
<% if !current_user %>
	<p><%= link_to 'Log in', login_path %> of <%= link_to 'meld je aan', new_user_registration_path %>.</p> 
<% end %>
<% if current_user %>
	<% if !@initiatives.empty? %>
		<h3>Mijn bucket Line<%= "s" if @initiatives.count > 1 %></h3>
		<div class="row">
			<div class="span12">
				<table class="table table-bordered table-striped">
					<tr>
						<th>Initiatief</th>
						<th>Locatie</th>
						<th>Omschrijving</th>
						<th>Mijn rol</th>
						<th></th>
						<th></th>
					</tr>

					<% @initiatives.each do |initiative| %>
						<tr>
							<td><%= initiative.name %></td>
							<td><%= initiative.location %></td>
							<td><%= initiative.description %></td>
							<% user_admin_role = current_user.initiative_admin(initiative) %>
							<td><%= if user_admin_role then 'admin' else 'bijdrager' end %></td>
							<td><%= link_to 'Bekijk kalender', initiative_projects_path(initiative) %></td>
							<td>
								<% if user_admin_role %>
									<%= link_to 'Bewerken', edit_initiative_path(initiative) %> | <%= link_to 'Verwijderen', initiative, confirm: 'Bucket Line wordt verwijderd inclusief alle klussen en benodigdheden. Dit kan niet ongedaan worden gemaakt. Weet je het echt zeker?', method: :delete %>
								<% end %>
							</td>
						</tr>
					<% end %>
				</table>
			</div>
		</div>
	<% else %>
		<div class="alert alert-block">
			<p style="font-weight:bold;">Je bent nog geen lid van een Bucket Line. Vraag een ander lid om een uitnodiging, of neem contact op met info@bucketline.nl om er zelf een te beginnen.</p>
		</div>
	<% end %>
	<% if current_user.super_admin %>
		<%= link_to 'Nieuwe Bucket Line aanmaken', new_initiative_path %>
	<% end %>
<% end %>

app/views/initiatives/index.html.haml
- content_for :header do
  = render :partial => "shared/site_admin_sub_nav" 

= link_to 'Nieuwe Bucket Line', new_initiative_path, class: "large button"
= link_to 'Nieuwe BL (Patient + Buddy)', new_with_buddy_initiatives_url(subdomain: false), class: "large button"
- if !@initiatives.empty?
  %table.admin-table
    %thead
      %tr
        %th Initiatief
        %th Locatie
        %th Omschrijving
        %th Mijn rol
        %th
        //%th
    %tbody
      - @initiatives.each do |initiative|
        %tr
          %td= initiative.name
          %td= initiative.location
          %td= initiative.description
          - user_admin_role = current_user.initiative_admin(initiative)
          %td= if user_admin_role then 'admin' else 'bijdrager' end
          %td= link_to 'Bekijk kalender', root_url(subdomain: initiative.slug)
          %td
            = link_to 'Verwijderen', initiative_url(subdomain: initiative.slug, id: initiative.id), confirm: 'Bucket Line wordt verwijderd inclusief alle klussen en benodigdheden. Dit kan niet ongedaan worden gemaakt. Weet je het echt zeker?', method: :delete

  .alert.alert-block
    %p{:style => "font-weight:bold;"} Je bent nog geen lid van een Bucket Line, lid worden van een Bucket Line gaat altijd op uitnodiging. Binnenkort nemen we contact me je op, om te kijken hoe we je verder kunnen helpen. Voor losse vragen kun je mailen met info@bucketline.nl

app/views/initiatives/new.html.erb
<h1>Nieuwe Bucket Line opzetten</h1>

<%= render 'form' %>

<%= link_to 'Terug', initiatives_path %>

app/views/initiatives/new.html.haml
- content_for :header do
  = render :partial => "shared/site_admin_sub_nav"

.row
  .six.columns
    = render 'form'

app/views/initiatives/new_bucket_group.html.haml
- content_for :header do
  = render :partial => "shared/bucket_group_sub_nav"

.row
  .six.columns
    %h3 Nieuwe Bucket Line
    = render 'form'
    = link_to 'Terug', admin_initiatives_path

app/views/initiatives/new_with_buddy.html.haml
- content_for :header do
  = render :partial => "shared/site_admin_sub_nav"

.row
  .six.columns
    = form_for @initiative, :url => {:controller => :initiatives, :action => :create_with_buddy} do |f|
      - if @initiative.errors.any?
        %h6.alert
          = pluralize(@initiative.errors.count, "fouten")

      = f.label :name_bucketline, class: form_error_class(@initiative.errors[:name])
      = f.text_field :name, class: form_error_class(@initiative.errors[:name])
      - if @initiative.errors[:slug].present?
        %small.error #{@initiative.errors[:slug].first}

      = f.label :location, class: form_error_class(@initiative.errors[:location])
      = f.text_field :location, class: form_error_class(@initiative.errors[:location])
      - if @initiative.errors[:location].present?
        %small.error #{@initiative.errors[:location].first}

      = f.label :description, class: form_error_class(@initiative.errors[:description])
      = f.text_area :description, class: form_error_class(@initiative.errors[:description])
      - if @initiative.errors[:description].present?
        %small.error #{@initiative.errors[:description].first}



      = f.label "Patiënt E-mail", class: form_error_class(@initiative.errors[:patient_email])
      = f.text_field :patient_email, class: form_error_class(@initiative.errors[:patient_email])
      - if @initiative.errors[:patient_email].present?
        %small.error #{@initiative.errors[:patient_email].first}

      = f.label "Patiënt naam", class: form_error_class(@initiative.errors[:patient_name])
      = f.text_field :patient_name, class: form_error_class(@initiative.errors[:patient_name])
      - if @initiative.errors[:patient_name].present?
        %small.error #{@initiative.errors[:patient_name].first}

      = f.label "Buddy E-mail", class: form_error_class(@initiative.errors[:buddy_email])
      = f.text_field :buddy_email, class: form_error_class(@initiative.errors[:buddy_email])
      - if @initiative.errors[:buddy_email].present?
        %small.error #{@initiative.errors[:buddy_email].first}

      = f.label "Buddy naam", class: form_error_class(@initiative.errors[:buddy_name])
      = f.text_field :buddy_name, class: form_error_class(@initiative.errors[:buddy_name])
      - if @initiative.errors[:buddy_name].present?
        %small.error #{@initiative.errors[:buddy_name].first}

      = f.submit "Maak Bucket Line", class: "button"

app/views/initiatives/show.html.erb
<% content_for :header do %>
  <% render :partial => "shared/sub_nav" %>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => "shared/initiative_side_menu" %>
<% end %>

<p><b>Naam:</b> <%= @initiative.name %><p>
<p><b>Omschrijving:</b> <%= @initiative.description %><p>
<p><b>Locatie:</b> <%= @initiative.location %><p>

<p><b>Bucket Line beheerders:</b> <%= @admin_names.to_sentence %>.</p>
<% if @user_names.count + @extra_user_count > 0 %>
	<p><b>Bucket Line leden:</b> <%= @user_names.to_sentence %><%= if @extra_user_count > 0 then (@user_names.count > 0 ? " en " : "") + @extra_user_count.to_s + " verborgen leden." end %></p>
<% end %>

<% if @user_role %>
	<p><%= link_to "Schrijf mij uit bij deze Bucket Line", user_role_path(@user_role), :method => :delete, :confirmation => "Weet je zeker dat je jezelf wilt uitschrijven bij deze Bucket Line?" %></p>
<% end %>