config/routes.rb
HvO::Application.routes.draw do

  constraints :subdomain => /.+/ do
    get '/' => 'initiatives#show'
    get '/wishlist' => "items#dashboard"
    get '/all_available_dates' => "available_dates#availability_dashboard"
    get '/profiles' => "profiles#index"

    
    get '/initiative/edit' => "initiatives#edit"
    delete '/initiative', :to => "initiatives#destroy"
    get '/initiative', :to => "initiatives#show"
    patch '/initiative', :to => "initiatives#update"
    resources :initiatives
    resources :invitations
  end
  root to: "home#index"

  get "/invitations/:token/accept", :to => "invitations#accept", :as => "accept_invitation"
  post "/invitations/:token", :to => "invitations#register", :as => "register_user_via_invitation"

  resources :initiatives do
    collection do
      get "new_from_bucket_group", :to => "initiatives#new_from_bucket_group"
      get "new_with_buddy", to: "initiatives#new_with_buddy"
      post "create_with_buddy", to: "initiatives#create_with_buddy"
    end
  end
  resources :bucket_groups, except: :index  do
    member do
      get 'admin_edit'
      delete 'destroy_user/:bgu_id', :to => "bucket_groups#destroy_user", as: "destroy_user"
    end
    collection do
      get "new_unregistered", :to => "bucket_groups#new_unregistered"
    end
    resources :invitations
  end

	get "waardeverbinder", :as => "waardeverbinder_info", :to => "waardeverbinder#info"
  get "disclaimer", :as => "disclaimer", :to => "home#disclaimer"

	post '/auth/:provider/callback' => 'authentications#create'

  resources :messages, :except => [:edit, :show]
	get "feedback" => "messages#new"

  get "profiles/all", :as => "all_profiles", :to => "profiles#super_admin_index"
  get "initiative_profiles", :as => "all_initiative_profiles", :to => "profiles#initiative_user_index"
  resources :profiles, :except => [:index] do
		resources :available_dates, :except => [:show]
    get "contribution" => "profiles#contribution"
	end
  

  devise_for :users, :skip => [:registrations]                                          
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
      patch 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
      delete 'users/:id' => 'devise/registrations#destroy'            
    end

	devise_scope :user do
		get "login", :to => "devise/sessions#new"
		get "logout", :to => "devise/sessions#destroy"
	end

  resources :user_roles, :except => [:show, :edit, :index] 
  get '/calendar(/:year(/:month))' => 'projects#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
	resources :items, :except => [:index, :show] #loose items
	get "dashboard", :to => "items#dashboard"
  get "availability_dashboard", :to => "available_dates#availability_dashboard"
	resources :links, :only => [:index]

  resources :projects, :except => [:show] do
    resources :items, :only => [:index, :update] #items belonging to projects
  end

  resources :messages, :except => [:index]

  scope "/admin" do
    resources :users
    get 'feedback', :to => 'messages#index', :as => "admin_feedback"
    get 'profiles', :to => "profiles#super_admin_index", :as => "admin_profiles"
    get 'initiatives', :to => "initiatives#index", :as => "admin_initiatives"
    get 'bucket_groups', to: "bucket_groups#index", :as => "admin_bucket_groups"
  end

	get "projects/info"
	get "available_dates/info"
	get "items/info"
	get "profiles/:id/info", :to => "profiles#info", :as => "profile_info"
	get "profiles/:profile_id/item/:id", :to => "profiles#remove_item", :as => "remove_item_from_profile"

  get "terms_and_conditions", :as => "terms_and_conditions", :to => "home#terms_and_conditions"

end

app/views/shared/_bucket_group_sub_nav.html.haml
.interior-header.profile
  .row
    .large-4.columns
      .title-text.white-text.hide-for-small
        = @bucket_group.name
    
    .large-8.columns
      %ul.inline-list
        %li
          = link_to "Leden", bucket_group_path(@bucket_group), class: is_current_page?(bucket_group_url(@bucket_group))
        
        - if current_user.bucket_group_admin?(@bucket_group)
          %li
            = link_to "Instellingen", edit_bucket_group_path(@bucket_group), class: is_current_page?(edit_bucket_group_url(@bucket_group))
        / %li
        /   = link_to "Instellingen", edit_user_registration_url(:subdomain => false), class: is_current_page?(edit_user_registration_url(:subdomain => false))

app/views/shared/_calendar.html.haml
.row
  .small-1.columns.previous-month
    = link_to "&lsaquo;".html_safe, {:month => @current_month.prev_month.month, :year => @current_month.prev_month.year}
  .small-10.columns.current-month
    %a.block{href:"#", "data-dropdown" => "dateDropdown"}
      %h4
        #{I18n.localize(@current_month, :format => "%B")} #{@current_month.year}
  .small-1.columns.next-month
    = link_to "&rsaquo;".html_safe, {:month => @current_month.next_month.month, :year => @current_month.next_month.year}

  = calendar(:year => year, :month => month, :first_day_of_week => 1, month_header: false) do |d|
    - render partial: 'calendar_item', locals: {date: d, events: events[d.day]}


%div#dateDropdown.f-dropdown.content{"data-dropdown-content" => ""}
  .row.year-control
    .small-4.columns
      .previous-year
        %a{href:"#"} &lsaquo;
    .small-4.columns
      .selected-year
        = @current_month.year
    .small-4.columns
      .next-year
        %a{href:"#"} &rsaquo;
  .row
    %ul.small-block-grid-3.month-block
      %li.month-button{"data-month" => 1} Jan
      %li.month-button{"data-month" => 2} Feb
      %li.month-button{"data-month" => 3} Mar
      %li.month-button{"data-month" => 4} Apr
      %li.month-button{"data-month" => 5} Mei
      %li.month-button{"data-month" => 6} Jun
      %li.month-button{"data-month" => 7} Jul
      %li.month-button{"data-month" => 8} Aug
      %li.month-button{"data-month" => 9} Sep
      %li.month-button{"data-month" => 10} Okt
      %li.month-button{"data-month" => 11} Nov
      %li.month-button{"data-month" => 12} Dec
  .row
    .small-12.columns.this-month
      = link_to "Deze maand", {:month => Date.today.month, :year => Date.today.year}

app/views/shared/_initiative_side_menu.html.haml
/ %ul.side-nav
/   %h4 
/     %small Navigatie
/   %li.divider
/   %li{class: get_active("calendar")}
/     = link_to "Kalender", projects_path
/   %li{class: get_active("dashboard")}
/     = link_to "Verlanglijstje", "/wishlist"
/   %li{class: get_active("availability")}
/     = link_to "Mijn beschikbaarheid", profile_available_dates_path(current_user)
/   %li{class: get_active("home")}
/     = link_to "Over deze Bucket Line", initiative_path

- if current_user.initiative_admin(@initiative)
  %ul.side-nav
    %h4 
      %small Admin
    %li.divider
    %li{class: (request.path == "/initiative/edit") ? "active" : ""}
      = link_to "Bucket Line instellingen", "/initiative/edit"
    %li{class: (request.path == "/profiles") ? "active" : ""}
      = link_to "Deelnemers beheer", "/profiles"
    %li{class: (request.path == "/all_available_dates") ? "active" : ""}
      = link_to "Alle beschikbaarheid", "/all_available_dates"
    %li{class: (request.path == "/links") ? "active" : ""}
      = link_to "Alle bijdragen", "/links"      

app/views/shared/_profile_sub_nav.html.haml
.interior-header.profile
  .row
    .large-4.columns
      .title-text.white-text.hide-for-small
        Mijn profiel
    
    .large-8.columns
      %ul.inline-list
        %li
          = link_to "Mijn profiel", edit_profile_url(current_user.profile, :subdomain => false), class: (request.path == edit_profile_path(current_user.profile)) ? "active" : ""
        %li
          = link_to "Instellingen", edit_user_registration_url(:subdomain => false), class: (request.path == edit_user_registration_path) ? "active" : ""

      / - if current_user.initiative_admin(@initiative)
      /   %ul.inline-list.admin
      /     %li
      /       = link_to "Bucket Line instellingen", "/initiative/edit", class: (request.path == "/initiative/edit") ? "active" : ""
      /     %li
      /       = link_to "Deelnemers beheer", "/profiles", class: (request.path == "/profiles") ? "active" : ""
      /     %li
      /       = link_to "Alle beschikbaarheid", "/all_available_dates", class: (request.path == "/all_available_dates") ? "active" : ""
      /     %li
      /       = link_to "Alle bijdragen", "/links", class: (request.path == "/links") ? "active" : ""

app/views/shared/_site_admin_sub_nav.html.haml
.interior-header.admin
  .row
    - if current_user.super_admin
      .large-4.columns
        .title-text.white-text.hide-for-small
          Administratie

      .large-8.columns
        %ul.inline-list
          %li
            = link_to "Bucket Lines", admin_initiatives_url(:subdomain => false), class: (request.path == admin_initiatives_path) ? "active" : ""
          %li
            = link_to "Preventieve Bucket Lines", admin_bucket_groups_url(:subdomain => false), class: (request.path == admin_bucket_groups_path) ? "active" : ""
          %li
            = link_to "Feedback berichten", admin_feedback_url(:subdomain => false), class: (request.path == admin_feedback_path) ? "active" : ""
          %li
            = link_to "Alle gebruikers", admin_profiles_url(:subdomain => false), class: (request.path == admin_profiles_path) ? "active" : ""

    - else
      .large-8.columns
        .title-text.white-text.hide-for-small
          Nieuwe Bucket Line

app/views/shared/_sub_nav.html.haml
.interior-header
  .row
    .large-4.columns
      .title-text.white-text.hide-for-small
        #{@initiative.name}
    
    .large-8.columns
      %ul.inline-list
        %li
          = link_to "Home", initiative_path,class: get_active("home")
        %li
          = link_to "Kalender", projects_path, class: get_active("calendar")
        %li
          = link_to "Verlanglijstje", "/wishlist", class: get_active("dashboard")
        - if current_user.initiative_admin(@initiative)  
          %li.admin-initiative-menu
            %a{href:"#", 'data-dropdown' => "drop1", 'data-options' => "is_hover:true", class: (request.path == "/initiative/edit" || request.path == "/profiles" || request.path == "/all_available_dates" || request.path == "/links") ? "active" : ""} Admin
            %ul#drop1.f-dropdown{'data-dropdown-content' => ""}
              %li
                = link_to "Bucket Line instellingen", "/initiative/edit"
              %li
                = link_to "Deelnemers beheer", "/profiles"
                
      / - if current_user.initiative_admin(@initiative)
      /   %ul.inline-list.admin
      /     %li
      /       = link_to "Bucket Line instellingen", "/initiative/edit", class: (request.path == "/initiative/edit") ? "active" : ""
      /     %li
      /       = link_to "Deelnemers beheer", "/profiles", class: (request.path == "/profiles") ? "active" : ""
      /     %li
      /       = link_to "Alle beschikbaarheid", "/all_available_dates", class: (request.path == "/all_available_dates") ? "active" : ""
      /     %li
      /       = link_to "Alle bijdragen", "/links", class: (request.path == "/links") ? "active" : ""

app/views/shared/_title.html.haml
.interior-header
  .large-3.columns
    .title-text.white-text.hide-for-small
      =yield (:title)
  .large-9.columns