config/routes.rb
HvO::Application.routes.draw do

  constraints :subdomain => /.+/ do
    get '/' => 'initiatives#show'
    get '/wishlist' => "items#dashboard"
    get '/all_available_dates' => "available_dates#availability_dashboard"
    get '/profiles' => "profiles#index"

    
    get '/initiative/edit' => "initiatives#edit"
    delete '/initiative', :to => "initiatives#destroy"
    get '/initiative', :to => "initiatives#show"
    patch '/initiative', :to => "initiatives#update"
    resources :initiatives
    resources :invitations
  end
  root to: "home#index"

  get "/invitations/:token/accept", :to => "invitations#accept", :as => "accept_invitation"
  post "/invitations/:token", :to => "invitations#register", :as => "register_user_via_invitation"

  resources :initiatives do
    collection do
      get "new_from_bucket_group", :to => "initiatives#new_from_bucket_group"
      get "new_with_buddy", to: "initiatives#new_with_buddy"
      post "create_with_buddy", to: "initiatives#create_with_buddy"
    end
  end
  resources :bucket_groups, except: :index  do
    member do
      get 'admin_edit'
      delete 'destroy_user/:bgu_id', :to => "bucket_groups#destroy_user", as: "destroy_user"
    end
    collection do
      get "new_unregistered", :to => "bucket_groups#new_unregistered"
    end
    resources :invitations
  end

	get "waardeverbinder", :as => "waardeverbinder_info", :to => "waardeverbinder#info"
  get "disclaimer", :as => "disclaimer", :to => "home#disclaimer"

	post '/auth/:provider/callback' => 'authentications#create'

  resources :messages, :except => [:edit, :show]
	get "feedback" => "messages#new"

  get "profiles/all", :as => "all_profiles", :to => "profiles#super_admin_index"
  get "initiative_profiles", :as => "all_initiative_profiles", :to => "profiles#initiative_user_index"
  resources :profiles, :except => [:index] do
		resources :available_dates, :except => [:show]
    get "contribution" => "profiles#contribution"
	end
  

  devise_for :users, :skip => [:registrations]                                          
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
      patch 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
      delete 'users/:id' => 'devise/registrations#destroy'            
    end

	devise_scope :user do
		get "login", :to => "devise/sessions#new"
		get "logout", :to => "devise/sessions#destroy"
	end

  resources :user_roles, :except => [:show, :edit, :index] 
  get '/calendar(/:year(/:month))' => 'projects#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
	resources :items, :except => [:index, :show] #loose items
	get "dashboard", :to => "items#dashboard"
  get "availability_dashboard", :to => "available_dates#availability_dashboard"
	resources :links, :only => [:index]

  resources :projects, :except => [:show] do
    resources :items, :only => [:index, :update] #items belonging to projects
  end

  resources :messages, :except => [:index]

  scope "/admin" do
    resources :users
    get 'feedback', :to => 'messages#index', :as => "admin_feedback"
    get 'profiles', :to => "profiles#super_admin_index", :as => "admin_profiles"
    get 'initiatives', :to => "initiatives#index", :as => "admin_initiatives"
    get 'bucket_groups', to: "bucket_groups#index", :as => "admin_bucket_groups"
  end

	get "projects/info"
	get "available_dates/info"
	get "items/info"
	get "profiles/:id/info", :to => "profiles#info", :as => "profile_info"
	get "profiles/:profile_id/item/:id", :to => "profiles#remove_item", :as => "remove_item_from_profile"

  get "terms_and_conditions", :as => "terms_and_conditions", :to => "home#terms_and_conditions"

end

app/models/project.rb
class Project
  include Mongoid::Document
 	include Mongoid::Timestamps
	include Mongoid::MultiParameterAttributes
	# include EventCalendar
	# has_event_calendar

	
	has_many :items, :autosave => true, :dependent => :delete
	belongs_to :owner, :class_name => "User", :inverse_of => :owned_projects
	belongs_to :initiative
	before_save :set_dates
	
	accepts_nested_attributes_for :items, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true

	validates_presence_of :query, :input_date, :input_start_at, :input_end_at
	validate :input_end_at_greater_than_input_start_at

	before_destroy :send_project_cancellation_mail

	field :query
	field :daypart #depricated
	field :input_date, :type => Date
	field :input_start_at, :type => Time
	field :input_end_at, :type => Time
	field :start_at, :type => DateTime
	field :end_at, :type => DateTime
	field :location, :type => String, :default => ""
	field :remark, :type => String
	field :success, :type => Mongoid::Boolean, :default => false
 
	def input_end_at_greater_than_input_start_at
	 unless self.input_end_at.to_i >= self.input_start_at.to_i
	   errors.add :input_end_at, "moet groter zijn dan begintijd"
	   return false
	 end
	 true
	end

	def set_dates
		unless input_date.nil? || input_start_at.nil? || input_end_at.nil?
			self.start_at = DateTime.new(input_date.year, input_date.month, input_date.day, input_start_at.hour, input_start_at.min)
			self.end_at = DateTime.new(input_date.year, input_date.month, input_date.day, input_end_at.hour, input_end_at.min)
		end
	end

	def self.events_for_date_range(start_d, end_d, find_options = {})
		where(find_options.merge(self.end_at_field.to_sym.lt => end_d.to_time.utc,
		self.start_at_field.to_sym.gt => start_d.to_time.utc)).asc(self.start_at_field)
	end

	def send_project_cancellation_mail
		mailing_list = self.contributor_emails
		if !mailing_list.empty?
			email = ProjectCancellationMailer.new(:initiative => self.initiative.name, :recipients => mailing_list, :admin_email => self.owner.email, :admin_contact => ("email: " + self.owner.email + ", tel: " + self.owner.profile.phone), :project_query => self.query, :project_start_at => self.start_at, :project_end_at => self.end_at)
			email.deliver
		end
	end

	#Items are updated after project is updated, so if this method is called by an after_create hook, project.items is old when the mail is sent. That's why it is called by the controller.
	def send_project_update_mail
		mailing_list = self.contributor_emails
		item_list = self.build_items_for_mailer
		if !mailing_list.empty?
			email = ProjectUpdateMailer.new(:initiative => self.initiative.name, :recipients => mailing_list, :admin_contact => ("email: " + self.owner.email + ", tel: " + self.owner.profile.phone), :admin_email => self.owner.email, :project_query => self.query, :items => item_list, :project_start_at => self.start_at, :project_end_at => self.end_at, :update_notice => true, :project_completion => (if self.success then "Afgerond" else "Onafgerond" end))
			email.deliver
		end
	end

	#Items are created after project is created, so if this method is called by an after_create hook, project.items is still empty when the mail is sent. That's why it is called by the controller.
	def send_project_placement_mail
		mailing_list = []
		item_list = self.build_items_for_mailer
		self.initiative.users.each do |user|
			if user.profile.always_send_project_placement_mail && user.email != self.owner.email #Get all the to-be-reminded-users that are not the owner of this project
				mailing_list << user.email
			end
		end
		email = ProjectPlacementMailer.new(:initiative => self.initiative.name, :recipients => mailing_list, :admin_email => self.owner.email, :admin_contact => ("email: " + self.owner.email + ", tel: " + self.owner.profile.phone), :location => self.location, :project_query => self.query, :project_start_at => self.start_at, :project_end_at => self.end_at, :items => item_list, :project_remark => self.remark)
		email.deliver
	end

	def build_items_for_mailer
		item_list = []
		self.items.all.each do |item|
			item_list << item.amount.to_s + " " + item.name
		end
		item_list.to_sentence
	end

	def providing_user(user) #checks if user is providing something for this project
		providing = false
		self.items.each do |item|
			if Link.where(:profile_id => user.profile.id, :item_id => item.id).count > 0
				providing = true
			end
		end
		providing
	end

	def contributor_emails
		mailing_list = []
		self.items.each do |item|
			links = item.links.all.entries
			if !links.empty?
				links.each do |link|
					if link.profile.send_project_cancellation_mail && self.owner != link.profile.user
						mailing_list << link.profile.user.email
					end
				end
			end
		end
		unique_mailing_list = mailing_list.uniq
	end

	def contributing_users
		users = []
		self.items.all.each do |item|
			item.links.all.each do |link|
				users << link.profile.user
			end
		end
		unique_users = users.uniq
	end

	def all_items_completed?
		self.items.each do |item|
			return false unless item.provided
		end
		return true
	end

	def project_completed?
		self.all_items_completed? || self.success
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # helper LaterDude::CalendarHelper

  before_filter :get_initiative
	before_filter :authenticate_admin_for_initiative, :except => [:index, :info]
  before_filter :authenticate_user_for_initiative, :only => [:index, :info]

  # GET /questions
  # GET /questions.json
  def index
		# session[:initiative_id] = params[:initiative_id]

		# @initiative = Initiative.where(slug: request.subdomain).first

    @month = (params[:month] || Time.zone.now.month).to_i
    @year = (params[:year] || Time.zone.now.year).to_i

    
    @current_month = Date.civil(@year, @month)
    @first_day_month = Date.civil(@year, @month)
    @last_day_month = Date.civil(@year, @month, -1) + 1

		@first_day_of_week = 1

    @events_hash = Array.new

    @events = @initiative.projects.where(:start_at.gte => @first_day_month, :start_at.lte => @last_day_month).asc(:start_at).each do |e|
      @events_hash[e.start_at.day] = [] if @events_hash[e.start_at.day].nil?;
      @events_hash[e.start_at.day].push(e)
    end

		# @event_strips = @initiative.projects.all.event_strips_for_month(@shown_month, @first_day_of_week)
    # @events_hash = @initiative.events_hash_for_month(@shown_month)
  end

	def info
		render :layout => false
	end

  def new
    @project = @initiative.projects.new
		@admins = @initiative.admins
    item = @project.items.build #appends an empty item to the form

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  def edit
    @project = Project.find(params[:id])
		@admins = @initiative.admins
  end

  def create
    @project = @initiative.projects.new(params[:project])
		@admins = @initiative.admins

    respond_to do |format|
      if @project.save
        #Mails for project creation are sent hourly by a rake task.
        format.html { redirect_to projects_path, notice: 'Het project is geplaatst' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @project = Project.find(params[:id])
    @admins = @initiative.admins

    respond_to do |format|
      if @project.update_attributes(params[:project])
        #Items are updated after project is updated, so if this method is called by an after_create hook, project.items is old when the mail is sent. That's why it is called by the controller.
        @project.send_project_update_mail
        format.html { redirect_to projects_path, notice: 'Het project is bijgewerkt' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def event_calendar
    calendar event_calendar_options do |args|
      event = args[:event] 
     	%(<a class="fancybox" href="/projects/#{event.id.to_s}/items?fancybox=true">#{build_event_text(event)}</a>)
    end
  end
end

app/views/projects/_calendar_item.html.haml
.calendar-day
  .day-label
    = date.day
  - if events.present?
    - events.each do |event|
      %a.event{href: project_items_path(event), "data-reveal-id" => "itemModal", "data-reveal-ajax" => "true"}
        - if event.project_completed?
          %i.green.fi-check.right{style:'margin-right:2px;'}
        - if current_user && event.providing_user(current_user)
          %i.red.fi-heart.right{style:'margin-right:2px;'}
        %ul.vcard
          %li.fn #{event.query}
          %li.time #{event.start_at.to_s(:time)} - #{event.end_at.to_s(:time)}

app/views/projects/_form.html.haml
= form_for(@project, :html => {:class => "custom"}) do |f| 
  - if @project.errors.any? 
    #error_explanation.alert
      %h2
        - if @project.errors.count > 0
          = pluralize(@project.errors.count, "error")
          = ":"

      %ul
        - @project.errors.full_messages.each do |msg| 
          = msg

  .row
    .small-12.large-6.columns

      = f.label 'Titel:' 
      = f.text_field :query 
      
      = f.label 'Datum:'  
      .row
        .small-12.columns
          = f.date_select(:input_date, {:default => @project.input_date || Date.parse(params[:date])}, {:class => "project_date date"})

      = f.label 'Begin:'  
      .row
        .small-12.columns
          = f.time_select(:input_start_at, {:minute_step => 15, time_separator: ''}, {class: "time"}) 

      = f.label 'Einde:'  
      .row.tim
        .small-12.columns
          = f.time_select(:input_end_at, {:minute_step => 15, time_separator: ''}, {class: "time"}) 

      = f.label "Verzamel locatie:" 
      = f.select(:location, [["Thuis", "Thuis"], ["Elders (zie opmerkingen)", "Elders (zie opmerkingen)"]]) 

      = f.label "Contactpersoon:" 
      = collection_select(:project, :owner_id, @admins, :id, :email, {:selected => current_user.id}) 

      = f.label 'Opmerkingen:'  
      = f.text_area :remark, :rows => 4 

      %label.checkbox
        = f.check_box :success 
        Klus is gedaan.

      = f.fields_for :items do |builder| 
        = render "item_fields", :f => builder

      = link_to_add_fields "Extra benodigdheid toevoegen", f, :items

    
      .row
        .small-12.columns
        - if request.path_parameters[:action] == 'new' then onclick_action = "_gaq.push(['_trackEvent', 'Project', 'Placement']);" else onclick_action = "" end 
      .row
        .small-12.columns
          = f.submit "Opslaan", :class => "button", :onclick => onclick_action 

app/views/projects/_item.html.erb
<blockquote>
	<% if item.provided %>
		<p><%= item.name %></p>
		<small><%= item.location %>, <%= item.start_at.to_s %> - <%= item.end_at.to_s %> - Deze bijdrage is al voorzien</small>
	<% else %>
		<%= form_tag project_item_path(item.project, item), :method => "put" do %>			
			<p><%= item.name %>, nog <%= item.amount.to_s %> te gaan</p>
			<small><%= item.location %>, <%= item.start_at.ctime.to_s %> - <%= item.end_at.ctime.to_s %></small>
			Aantal: <%= text_field_tag 'amount_to_give', 1, :class => "amount-input" %> <%= submit_tag "Dit wil ik bijdragen!" %>
		<% end %>
	<% end %>
	<% if user_signed_in? %>
		<%= link_to "Item of bijbehorende project bewerken", edit_project_path(item.project) %>
	<% end %>
</blockquote>

app/views/projects/_item_fields.html.haml
.panel
	= f.label :name, "Klus: (verplicht veld)", :class => "control-label"
	= f.text_field :name

	= f.label :type, "Type:", :class => "control-label"
	= f.select :type, [['Vervoer', 'vervoer'],['In en om het huis', 'in en om het huis'],['Oppas en gezelschap','oppas en gezelschap'],['Boodschappen en koken','boodschappen en koken']]
				
	= f.label :amount, "Aantal:", :class => "control-label"
	= f.text_field :amount

	= link_to_remove_fields "Verwijder klus", f

app/views/projects/edit.html.haml
- content_for :header do
  = render :partial => "shared/sub_nav" 

- content_for :sidebar do
  = render :partial => "shared/initiative_side_menu"

%h3 Klus en benodigdheden bewerken
= render 'form'

app/views/projects/index.html.haml
- content_for :header do
  = render :partial => "shared/sub_nav" 

= hidden_field_tag "initiativeAdmin", current_user.initiative_admin(@initiative) 

.row
  .small-12.columns
    - if @initiative.projects.count == 0
      - if current_user.initiative_admin(@initiative)
        = alert("Er zijn nog geen taken in de kalender geplaatst. Klik op een dag om een taak te plaatsen.","",true)
      - else
        = alert("Er zijn nog geen taken in de kalender geplaatst. Een beheerder moet eerst een taak plaatsen voor je kunt bijdragen.","",true)

#projectCalendar
  = render partial: 'shared/calendar', locals: {year: @year, month: @month, events: @events_hash}

#itemModal.reveal-modal

app/views/projects/info.html.erb
<div class="info">
	<p>In de kalender staan alle klussen die op stapel staan. Klik op een klus om te zien wat er nog nodig is.</p>
	<p>Je kunt je aanmelden om een bijdrage te leveren door het aantal in te vullen en te klikken op "Dit wil ik bijdragen!"</p>
	<p>In <%= link_to "je profiel", profile_path(current_user.profile) %> vind je een overzicht van al je bijdragen.</p>
	<p>Als je aan een klus hebt bijgedragen komt er een cadeautje bij te staan. Zo kun je snel zien bij welke klussen je betrokken bent. Als een klus al is gedaan, dan komt er een vinkje bij te staan. Je kunt dan niet meer bijdragen aan deze klus.</p>
</div>

app/views/projects/new.html.haml
- content_for :header do
  = render :partial => "shared/sub_nav" 

- content_for :sidebar do
  = render :partial => "shared/initiative_side_menu"

%h3 Nieuwe klus
= render 'form'