config/routes.rb
HvO::Application.routes.draw do

  constraints :subdomain => /.+/ do
    get '/' => 'initiatives#show'
    get '/wishlist' => "items#dashboard"
    get '/all_available_dates' => "available_dates#availability_dashboard"
    get '/profiles' => "profiles#index"

    
    get '/initiative/edit' => "initiatives#edit"
    delete '/initiative', :to => "initiatives#destroy"
    get '/initiative', :to => "initiatives#show"
    patch '/initiative', :to => "initiatives#update"
    resources :initiatives
    resources :invitations
  end
  root to: "home#index"

  get "/invitations/:token/accept", :to => "invitations#accept", :as => "accept_invitation"
  post "/invitations/:token", :to => "invitations#register", :as => "register_user_via_invitation"

  resources :initiatives do
    collection do
      get "new_from_bucket_group", :to => "initiatives#new_from_bucket_group"
      get "new_with_buddy", to: "initiatives#new_with_buddy"
      post "create_with_buddy", to: "initiatives#create_with_buddy"
    end
  end
  resources :bucket_groups, except: :index  do
    member do
      get 'admin_edit'
      delete 'destroy_user/:bgu_id', :to => "bucket_groups#destroy_user", as: "destroy_user"
    end
    collection do
      get "new_unregistered", :to => "bucket_groups#new_unregistered"
    end
    resources :invitations
  end

	get "waardeverbinder", :as => "waardeverbinder_info", :to => "waardeverbinder#info"
  get "disclaimer", :as => "disclaimer", :to => "home#disclaimer"

	post '/auth/:provider/callback' => 'authentications#create'

  resources :messages, :except => [:edit, :show]
	get "feedback" => "messages#new"

  get "profiles/all", :as => "all_profiles", :to => "profiles#super_admin_index"
  get "initiative_profiles", :as => "all_initiative_profiles", :to => "profiles#initiative_user_index"
  resources :profiles, :except => [:index] do
		resources :available_dates, :except => [:show]
    get "contribution" => "profiles#contribution"
	end
  

  devise_for :users, :skip => [:registrations]                                          
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
      patch 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
      delete 'users/:id' => 'devise/registrations#destroy'            
    end

	devise_scope :user do
		get "login", :to => "devise/sessions#new"
		get "logout", :to => "devise/sessions#destroy"
	end

  resources :user_roles, :except => [:show, :edit, :index] 
  get '/calendar(/:year(/:month))' => 'projects#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
	resources :items, :except => [:index, :show] #loose items
	get "dashboard", :to => "items#dashboard"
  get "availability_dashboard", :to => "available_dates#availability_dashboard"
	resources :links, :only => [:index]

  resources :projects, :except => [:show] do
    resources :items, :only => [:index, :update] #items belonging to projects
  end

  resources :messages, :except => [:index]

  scope "/admin" do
    resources :users
    get 'feedback', :to => 'messages#index', :as => "admin_feedback"
    get 'profiles', :to => "profiles#super_admin_index", :as => "admin_profiles"
    get 'initiatives', :to => "initiatives#index", :as => "admin_initiatives"
    get 'bucket_groups', to: "bucket_groups#index", :as => "admin_bucket_groups"
  end

	get "projects/info"
	get "available_dates/info"
	get "items/info"
	get "profiles/:id/info", :to => "profiles#info", :as => "profile_info"
	get "profiles/:profile_id/item/:id", :to => "profiles#remove_item", :as => "remove_item_from_profile"

  get "terms_and_conditions", :as => "terms_and_conditions", :to => "home#terms_and_conditions"

end

app/models/bucket_group.rb
class BucketGroup
  include Mongoid::Document
  include Mongoid::Timestamps

  before_save :build_slug

  field :name, type: String
  field :description, type: String
  field :slug, type: String

  embeds_many :users, class_name: "BucketGroupUser", cascade_callbacks: true
  has_many :invitations, :dependent => :destroy, as: :invitationable

  accepts_nested_attributes_for :users

  validates_presence_of :name
  validates_uniqueness_of :name, :slug
  # validates_format_of :creator_email, with: /\A(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Z‌​a-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6}\z/i, message: "Geen geldig e-mail adres"

  attr_accessor :creator_email, :creator_password, :creator_password_confirmation, :creator_name, :new_registration

  def user_is_member?(user)
    self.users.where(user_id: user.id).present?
  end

  def user_is_admin?(user)
    (self.users.where(user_id: user.id).present? and self.users.where(user_id: user.id).first.admin) || user.super_admin
  end

  private

  def build_slug
    self.slug = self.name.parameterize
  end
  
end

app/controllers/bucket_groups_controller.rb
class BucketGroupsController < ApplicationController
  before_filter :get_bucket_group, only: [:show, :settings, :edit, :admin_edit, :update, :destroy_user]
  before_filter :authenticate_super_admin, :only => [:index, :new]
  before_filter :authenticate_user_for_bucket_group, except: [:new_unregistered, :create]
  before_filter :authenticate_admin_for_bucket_group, except: [:show, :new_unregistered, :create]

  def index
    @bucket_groups = BucketGroup.all
  end

  def new
    @bucket_group = BucketGroup.new
  end

  def new_unregistered
    @bucket_group = BucketGroup.new
  end

  def edit
    # @bucket_group = BucketGroup.find(params[:id])
  end

  def admin_edit
    # @bucket_group = BucketGroup.find(params[:id])
  end

  def show
  end

  def settings
  end

  def create
    @bucket_group = BucketGroup.new(params[:bucket_group])

    if params[:bucket_group][:new_registration]
      user = User.new( email: params[:bucket_group][:creator_email],
                          name: params[:bucket_group][:creator_name],
                          password: params[:bucket_group][:creator_password],
                          password_confirmation: params[:bucket_group][:creator_password_confirmation] 
        )
      if @bucket_group.valid?
        user.save
      end
    else
      user = current_user
    end

    @bucket_group.errors[:creator_name] = user.errors[:name]
    @bucket_group.errors[:creator_email] = user.errors[:email]
    @bucket_group.errors[:creator_password] = user.errors[:password]
    @bucket_group.errors[:creator_password_confirmation] = user.errors[:password_confirmation]

    respond_to do |format|
      if !(user.errors.count > 0) and @bucket_group.save
        @bucket_group.users.create(:user_id => user.id, :admin => true)
        format.html do
          if current_user.present?
            redirect_to admin_bucket_groups_url(:subdomain => false), :notice => "Preventieve Bucket Line is aangemaakt."
          else
            redirect_to login_path, notice: "Je nieuwe preventieve Bucket Line is aangemaakt. Een bericht met een bevestigingslink is verstuurd naar je e-mail adres. Klik op deze link om je aanmelding te bevestigen."
          end
        end
      else
        
        format.html do
          if current_user.present?
            render action: "new"
          else
            render action: "new_unregistered"
          end
        end
        format.json { render json: @bucket_group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # @bucket_group = BucketGroup.find(params[:id])

    respond_to do |format|
      if @bucket_group.update_attributes(params[:bucket_group])
        format.html {render action: :show, notice: "Preventieve Bucket Line geupdatet"}
      else
        format.html {render action: :show, alert: "Preventieve Bucket Line niet geupdatet."}
      end
    end
  end

  def destroy
    BucketGroup.find(params[:id]).destroy
    respond_to do |format|
      format.html {redirect_to :back, notice: "Preventieve Bucket Line verwijderd."}
    end
  end

  def destroy_user
    BucketGroup.find(params[:id]).users.find(params[:bgu_id]).delete
    respond_to do |format|
      format.html {redirect_to :back, notice: "Preventieve Bucket Line gebruiker verwijderd."}
    end
  end

  private

  def get_bucket_group
    @bucket_group = if BucketGroup.where(_id: params[:id]).exists?
      BucketGroup.find(params[:id]) 
    else
      BucketGroup.find_by(slug: params[:id])
    end
  end

end

app/helpers/bucket_groups_helper.rb
module BucketGroupsHelper
end

app/views/bucket_groups/_form.html.haml
= form_for @bucket_group do |f|
  .row
    .small-12.large-6.columns
      
      = f.label :name
      = f.text_field :name

      = f.label :description
      = f.text_field :description
      
      = f.submit class: "button"

app/views/bucket_groups/_form_unregistered.html.haml
= form_for @bucket_group, :builder => ApplicationHelper::BetterFormBuilder do |f|
  .row
    .small-12.large-6.columns

      - @object = @bucket_group

      = f.hidden_field :new_registration, value: true

      = f.label :creator_name, "Jouw naam"
      = f.text_field :creator_name
      = f.field_error :creator_name

      = f.label :creator_email, "Jouw email"
      = f.email_field :creator_email
      = f.field_error  :creator_email

      = f.label :creator_password, "Je wachtwoord"
      = f.password_field :creator_password
      = f.field_error  :creator_password

      = f.label :creator_password_confirmation, "Je wachtwoord nogmaals"
      = f.password_field :creator_password_confirmation
      = f.field_error  :creator_password_confirmation
      
      = f.label :name, "Naam Bucketgroup"
      = f.text_field :name
      = f.field_error :name

      = f.label :description, "Beschrijving Bucketgroup"
      = f.text_area :description
      = f.field_error :decription
      
      = f.submit "Maak preventieve Bucket Line", class: "button"

app/views/bucket_groups/admin_edit.html.haml
- content_for :header do
  = render :partial => "shared/site_admin_sub_nav" 

= render :partial => "form" 

app/views/bucket_groups/edit.html.haml
- content_for :header do
  = render :partial => "shared/bucket_group_sub_nav" 

= render :partial => "form" 

app/views/bucket_groups/index.html.haml
- content_for :header do
  = render :partial => "shared/site_admin_sub_nav" 

= link_to 'Nieuwe Preventieve Bucket Line', new_bucket_group_path, class: "large button"
  
%table.admin-table
  %thead
    %tr
      %th Preventieve Bucket Line
      %th Omschrijving
      %th
  %tbody
    - @bucket_groups.each do |group|
      %tr
        %td= link_to group.name, bucket_group_url(group)
        %td= group.description            
        %td
          = link_to 'Bewerken', admin_edit_bucket_group_url(group)
          |
          = link_to 'Verwijderen', bucket_group_url(group), confirm: 'Weet je zeker dat je deze preventieve Bucket Line wilt verwijderen? Dit kan niet ongedaan gemaakt worden!', method: :delete

app/views/bucket_groups/new.html.haml
- content_for :header do
  = render :partial => "shared/site_admin_sub_nav" 

= render :partial => "form" 

app/views/bucket_groups/new_unregistered.html.haml
- content_for :header do
  .interior-header
    .row
      .large-8.columns
        .title-text.white-text.hide-for-small
          Nieuwe preventieve Bucket Line

%p We geven mensen, bijvoorbeeld buurtverenigingen, ook de mogelijkheid een preventieve Bucket Line op te zetten. Wanneer er een persoonlijke noodsituatie zich voordoet kun je dan heel makkelijk vanuit de Preventieve Bucket Line een Bucket Line aanmaken met de verzamelde mensen erin!

= render :partial => "form_unregistered" 

app/views/bucket_groups/show.html.haml
- content_for :header do
  = render :partial => "shared/bucket_group_sub_nav"

- if current_user.bucket_group_admin?(@bucket_group)
  = link_to 'Gebruiker uitnodiging', new_bucket_group_invitation_path(@bucket_group), :class => "large button"
  = link_to 'Nieuwe Bucket Line', new_from_bucket_group_initiatives_path(bucket_group_id: @bucket_group.id), class: "large button"

- if @bucket_group.user_is_admin?(current_user)
  
  = form_for @bucket_group do |f|

    %table.admin-table
      %tr
        %th Naam
        %th Expertise
        %th Kan helpen met
        %th Handige spullen in bezit
        %th Telefoon
        %th Email
        %th Buddy bereidheid
        %th Admin
        %th 
      = f.fields_for :users do |bgu|
        - if bgu.object.user.present?
          %tr
            %td= bgu.object.user.name
            %td= bgu.object.user.profile.expertise if bgu.object.user.profile
            %td= bgu.object.user.profile.willing_to_help_with if bgu.object.user.profile
            %td= bgu.object.user.profile.tools_and_materials if bgu.object.user.profile
            %td= bgu.object.user.profile.phone if bgu.object.user.profile
            %td= bgu.object.user.email
            %td= "Ja" if bgu.object.user.profile && bgu.object.user.profile.willing_to_become_admin
            %td
              - if bgu.object.user != current_user      
                = bgu.check_box :admin
              - else
                = bgu.check_box :admin, disabled: true
            %td
              = link_to "Verwijderen", destroy_user_bucket_group_path(@bucket_group, bgu.object), :method => :delete, :confirm => "Weet je zeker dat je deze gebruiker uit deze Bucket Line wilt verwijderen?"
        - else
          - bgu.object.destroy

    = f.submit "Update", :class => "button", :confirm => "Weet je zeker dat je de rechten van deze gebruiker wilt aanpassen?"



- else

  %h3 Admins
  %dl
    - @bucket_group.users.includes(:user).where(admin: true).each do |user|
      %dt= user.user.name

  %h3 Leden
  %dl
    - @bucket_group.users.includes(:user).where(admin: false).each do |user|
      %dt= user.user.name